In [1]:
import geopandas as gpd
import pandas as pd
import os,re,json
import numpy as np
from p_tqdm import p_map

In [2]:
oa11 = gpd.read_file('data/OA2011.geojson')
oa01 = gpd.read_file('data/OA2001.geojson')

In [3]:
oa01

OBJECTID     OA01CD   OA01CDOLD   Shape__Area  Shape__Length  \
0              1  E00122082  29UCGD0009  9.576393e+05    6299.071544   
1              2  E00000001  00AAFA0001  6.790870e+03     428.006637   
2              3  E00000002  00AAFA0002  1.075229e+04     722.820786   
3              4  E00000003  00AAFA0003  4.367502e+03     321.203321   
4              5  E00000004  00AAFA0004  9.075270e+03     382.664679   
...          ...        ...         ...           ...            ...   
175429    175430  E00035620  00CAGN0036  1.485545e+06    7059.899583   
175430    175431  E00035616  00CAGN0032  1.575351e+05    2386.443107   
175431    175432  E00035615  00CAGN0031  1.640965e+05    3139.907722   
175432    175433  E00035617  00CAGN0033  3.357877e+05    3242.244346   
175433    175434  E00035619  00CAGN0035  1.454532e+05    3742.448667   

                                                 geometry  
0       POLYGON ((1.11616 51.29039, 1.11636 51.29013, ...  
1       POLYGON ((-0.09648 51.52024, -0.09649 51.52028...  
2       POLYGON ((-0.09649 51.52028, -0.09648 51.52024...  
3       POLYGON ((-0.09702 51.51968, -0.09648 51.52024...  
4       POLYGON ((-0.09627 51.51914, -0.09627 51.51933...  
...                                                   ...  
175429  POLYGON ((-3.05572 53.51949, -3.05510 53.51943...  
175430  POLYGON ((-3.05708 53.52067, -3.05709 53.52073...  
175431  POLYGON ((-3.05888 53.52082, -3.05896 53.52081...  
175432  POLYGON ((-3.06150 53.52149, -3.06139 53.52153...  
175433  MULTIPOLYGON (((-3.07093 53.52154, -3.07115 53...  

[175434 rows x 6 columns]

In [4]:
c11 = gpd.read_file('data/centroids2011.geojson')
c01 = gpd.read_file('data/centroids2001.geojson')

m11 = gpd.read_file('data/centroids2011.geojson').to_crs('EPSG:5234')
m01 = gpd.read_file('data/centroids2001.geojson').to_crs('EPSG:5234')


In [5]:
# distances=[]
# ids =[]
# for _,i in m11.iterrows():
    
#     m01['dist']= m01.geometry.apply(lambda s: i.geometry.distance(s))
    
#     mval = m01.sort_values('dist').reset_index().iloc[0]
#     ids.append(mval['OA01CD'])
#     distances.append(mval['dist'])
    
# m11['m01'] = ids
# m11['distance'] = distances

# m11

In [6]:
values = list(m11.iterrows())

def dist (j):
    _,i=j
    
    df = abs(m01.geometry.y - i.geometry.y)
    
    m01['dist'] = df #m01.geometry.distance(i.geometry)
    
    mval = m01.sort_values('dist').reset_index().iloc[:50]
    
    
    mval['dist'] = mval.geometry.distance(i.geometry)
    
    mval = mval.sort_values('dist').reset_index().iloc[0]
    
    
    return [mval['OA01CD'],mval['dist']]
    
    
res =  p_map(dist,values)
res

  0%|          | 0/34378 [00:00<?, ?it/s]

Process ForkPoolWorker-14:
Process ForkPoolWorker-11:
Process ForkPoolWorker-1:
Process ForkPoolWorker-12:
Process ForkPoolWorker-13:
Process ForkPoolWorker-6:
Process ForkPoolWorker-8:
Process ForkPoolWorker-2:
Process ForkPoolWorker-4:
Process ForkPoolWorker-9:
Process ForkPoolWorker-7:
Process ForkPoolWorker-5:
Process ForkPoolWorker-16:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/multiprocess/process.py", line 315, i

  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/geopandas/base.py", line 74, in _delegate_property
    data = getattr(a_this, op)
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/geopandas/array.py", line 671, in y
    return vectorized.get_y(self.data)
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/geopandas/array.py", line 671, in y
    return vectorized.get_y(self.data)
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/geopandas/array.py", line 671, in y
    return vectorized.get_y(self.data)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/geopandas/array.py", line 671, in y
    return vectorized.get_y(self.data)
  File "/Users/danielellis/opt/minicond

  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/shapely/geometry/base.py", line 432, in geom_type
    return self.geometryType()
  File "/var/folders/h8/t803dxss41g9kj07lkgx95fm0000gn/T/ipykernel_8160/3141744278.py", line 6, in dist
    df = abs(m01.geometry.y - i.geometry.y)
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/shapely/geometry/point.py", line 60, in y
    return self.coords[0][1]
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/shapely/geometry/base.py", line 330, in _get_coords
    if self.is_empty:
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/multiprocess/pool.py", line 125, in worker
    result = (

  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/shapely/geos.py", line 581, in errcheck_predicate
    def errcheck_predicate(result, func, argtuple):
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/geopandas/base.py", line 74, in _delegate_property
    data = getattr(a_this, op)
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/shapely/topology.py", line 17, in _validate
    if ob is None or ob._geom is None:
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "/var/folders/h8/t803dxss41g9kj07lkgx95fm0000gn/T/ipykernel_8160/3141744278.py", line 6, in dist
    df = abs(m01.geometry.y - i.geometry.y)
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/geopandas/base.py", line 74, in _delegate_property
    data = getattr(a_this, op)
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages

  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/shapely/geometry/base.py", line 330, in _get_coords
    if self.is_empty:
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/shapely/geometry/base.py", line 332, in _get_coords
    return CoordinateSequence(self)
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/geopandas/_vectorized.py", line 451, in <listcomp>
    data = [getattr(geom, op, null_value) for geom in left]
KeyboardInterrupt
KeyboardInterrupt
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/geopandas/_vectorized.py", line 451, in <listcomp>
    data = [getattr(geom, op, null_value) for geom in left]
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/shapely/coords.py", line 49, in __len__
    self._update()
  File "/Users/danielellis/opt/miniconda3/lib/python3.9/site-packages/shapely/geometry/point.py", line 60, in y
    return self.coords[0][1]
  File "/Users/danielellis/opt

KeyboardInterrupt: 

In [ ]:
c01.head()

In [ ]:
c11.head()

In [ ]:
c11[c11['lsoa01cd']=='E00000001']

In [21]:
p1 = c11.iloc[1].geometry
p2 = c11.iloc[4].geometry

p1.distance(p2)

0.01865113280962705

In [78]:

m11.shape[0]*m01.shape[0]


6031070052

In [ ]:
m11.distance(p1)

In [ ]:
((p1-p2).xy)

In [ ]:
p1.y-p2.y

In [ ]:
p1.y

In [67]:

# def cosine_similarity(x, y):
#     return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))


def cart(lat,lon):
    R = 637800 #earth radius in m
    x = R * np.cos(lat) * np.cos(lon)
    y = R * np.cos(lat) * np.sin(lon)
    z = R * np.sin(lat)
    return x,y,z

def get_coord(x):
    return np.array([cart(*i.xy) for i in x.geometry])[:,:,0]

from sklearn.neighbors import KDTree

X11 = get_coord(c11)  #
X01 = get_coord(c01) 
tree = KDTree(X11, leaf_size=2)  





dist, ind = tree.query([X01[199]], k=3)                
print(ind,dist)  # indices of 3 closest neighbors


[[40 44 45]] [[1020.30820012 1781.57574803 3313.38610026]]


In [47]:
# trims , leaves, splits
tree.get_tree_stats()


(19, 4, 22)

In [57]:
np.array(tree.node_bounds).shape

(2, 32767, 3)

In [65]:
np.array(tree.node_bounds).shape

(2, 32767, 3)

In [39]:
m01.iloc[1].geometry.distance(m11.iloc[1].geometry
)


448.49010175900776

In [83]:

tree.query([X11[199]], k=3) 



(array([[   0.        , 2894.20973742, 3261.12245578]]),
 array([[199, 200, 198]]))

In [ ]:



Your points are in a lon, lat coordinate system (EPSG:4326 or WGS 84). To calculate a distance in meters, you would need to either use the Great-circle distance or project them in a local coordinate system to approximate the distance with a good precision.

For Sri Lanka, you can use EPSG:5234 and in GeoPandas, you can use the distance function between two GeoDataFrames.